// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ShortLink struct {
	ID          int64
	ShortCode   string
	OriginalUrl string
	ExpiresAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	IsActive    pgtype.Bool
}

type User struct {
	ID           int64
	Email        string
	PasswordHash pgtype.Text
	FirstName    pgtype.Text
	LastName     pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
