// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shortlink.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

const createShortLink = `-- name: CreateShortLink :exec
INSERT INTO short_links (
  short_code, 
  original_url, 
  expires_at
) VALUES (
  $1, $2, $3
)
`

type CreateShortLinkParams struct {
	ShortCode   string
	OriginalUrl string
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreateShortLink(ctx context.Context, arg CreateShortLinkParams) error {
	_, err := q.db.Exec(ctx, createShortLink, arg.ShortCode, arg.OriginalUrl, arg.ExpiresAt)
	return err
}

const getOriginalURLByCode = `-- name: GetOriginalURLByCode :one
SELECT original_url
FROM short_links
WHERE short_code = $1
  AND is_active = TRUE
  AND (expires_at IS NULL OR expires_at > NOW())
LIMIT 1
`

func (q *Queries) GetOriginalURLByCode(ctx context.Context, shortCode string) (string, error) {
	row := q.db.QueryRow(ctx, getOriginalURLByCode, shortCode)
	var originalURL string
	err := row.Scan(&originalURL)
	if err == pgx.ErrNoRows {
		return "", err
	}
	return originalURL, err
}
