// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT id, email
FROM users
WHERE id = $1
`

type GetUserRow struct {
	ID    int64
	Email string
}

func (q *Queries) GetUser(ctx context.Context, id int64) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}
